#!/bin/bash
# -*- compile-command: "PRXPTY=~/prxpty/ ./chk src/node_modules/log.ls"; -*-
set -e

function post_traverse_dir {

  # descend tree
  local TREE=$1
  local DIR
  for DIR in $(find $TREE -mindepth 1 -maxdepth 1 -type d); do
    post_traverse_dir $DIR
  done

  # execute test scripts
  find $TREE -mindepth 1 -maxdepth 1 \
       -regex '.*_[0-9]+.*' -and -not -type d | \
    sort -t _ -n -k 2
}

function filename_to_associated_tests {
  TARGETDIR=$(dirname $TARGET)
  find $TARGETDIR -mindepth 1 -maxdepth 1 \
       -regex "${TARGET}_[0-9]+.*" -and -not -type d | \
    sort -t _ -n -k 2
}

TARGET=$1
if [ -z "$TARGET" ] ; then
  TARGET=src
fi
if [ -d "$TARGET" ] ; then
  for FILE in $(post_traverse_dir $TARGET) ; do
    echo "[TEST] chk: exec $FILE"
    $(readlink -f $FILE) 2>&1
  done
  exit 0
fi
if [ -f "$TARGET" ] ; then

  # run file itself if test
  if [[ "$TARGET" =~ .*_[0-9]+\.test\..* ]] ; then
    echo "[TEST] chk: exec $TARGET"
    $(readlink -f $TARGET) 2>&1
    exit 0
  fi

  # otherwise run associated tests
  for FILE in $(filename_to_associated_tests $TARGET) ; do
    echo "[TEST] chk: exec $FILE"
    $(readlink -f $FILE) 2>&1
  done
  exit 0
fi

echo "[FAIL] chk: invalid test target $TARGET"
exit 1
